"""added columns with requests

Revision ID: 085d35f8d8b9
Revises: 84590517e935
Create Date: 2020-06-27 15:22:23.078106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085d35f8d8b9'
down_revision = '84590517e935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('requests_user_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('requests_user_fkey', 'users', ['user'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
