"""change pricelevel to integer

Revision ID: 137ab115550a
Revises: bb1ff3501b7f
Create Date: 2020-06-17 17:43:13.243098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137ab115550a'
down_revision = 'bb1ff3501b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('price_level',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('price_level',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
