"""added newsletter subscr to users table

Revision ID: 183dd53cddbc
Revises: 4f11bca48ad9
Create Date: 2020-06-19 11:48:52.679769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183dd53cddbc'
down_revision = '4f11bca48ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('newsletter',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('newsletter',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
