"""added newsletter subscr to users table

Revision ID: 4f11bca48ad9
Revises: d847613449ee
Create Date: 2020-06-19 11:47:40.208153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f11bca48ad9'
down_revision = 'd847613449ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newsletter', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('newsletter')

    # ### end Alembic commands ###
