"""added doubles table and made relationship

Revision ID: 67aaac79ce03
Revises: ef1f0ead8447
Create Date: 2020-08-05 14:54:50.284195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67aaac79ce03'
down_revision = 'ef1f0ead8447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('double',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=128), nullable=False),
    sa.Column('double_place_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('double')
    # ### end Alembic commands ###
