"""add processed colum with requests

Revision ID: 92dd82d07f8e
Revises: 41c16574e6fe
Create Date: 2020-06-23 22:10:11.974872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92dd82d07f8e'
down_revision = '41c16574e6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('processed', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('processed')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
