"""change user model roles list

Revision ID: a3949e468ce9
Revises: 113d1b4d69bf
Create Date: 2020-05-18 21:09:00.123254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3949e468ce9'
down_revision = '113d1b4d69bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('price_level',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=True)
        batch_op.alter_column('review',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('tip',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('tip',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('review',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.alter_column('price_level',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
