"""added videolength to highlight

Revision ID: b04fcc0e2dc2
Revises: a8574e81633c
Create Date: 2020-08-22 14:19:59.739551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04fcc0e2dc2'
down_revision = 'a8574e81633c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.add_column(sa.Column('videolength', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('highlights', schema=None) as batch_op:
        batch_op.drop_column('videolength')

    # ### end Alembic commands ###
