"""added hidden location table

Revision ID: c45afcc85998
Revises: d367532baa18
Create Date: 2020-07-11 16:05:54.077927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45afcc85998'
down_revision = 'd367532baa18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hidden',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hidden')
    # ### end Alembic commands ###
