"""change double table name

Revision ID: d0c3b52ea7cc
Revises: 67aaac79ce03
Create Date: 2020-08-05 15:04:48.664983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c3b52ea7cc'
down_revision = '67aaac79ce03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doubles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=128), nullable=False),
    sa.Column('double_place_id', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('double')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('double',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recommendation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('place_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('double_place_id', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], name='double_recommendation_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='double_pkey')
    )
    op.drop_table('doubles')
    # ### end Alembic commands ###
