"""added newsletter send column

Revision ID: d847613449ee
Revises: d0f302b1bfc7
Create Date: 2020-06-18 20:55:41.456551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd847613449ee'
down_revision = 'd0f302b1bfc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.drop_column('send')

    # ### end Alembic commands ###
