"""added newsletter table and changed blog friday review

Revision ID: e03ffe660db5
Revises: 137ab115550a
Create Date: 2020-06-18 17:27:58.987358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e03ffe660db5'
down_revision = '137ab115550a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newsletters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short', sa.Text(), nullable=False))
        batch_op.alter_column('body',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_column('img')

    with op.batch_alter_table('friday_tips', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('checked')

    with op.batch_alter_table('friday_tips', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('short')

    op.drop_table('newsletters')
    # ### end Alembic commands ###
