"""added errorlog table

Revision ID: e309f76b2cf5
Revises: 1334ff18b9ab
Create Date: 2020-07-07 14:47:05.821778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e309f76b2cf5'
down_revision = '1334ff18b9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logger', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=100), nullable=True),
    sa.Column('trace', sa.String(length=4096), nullable=True),
    sa.Column('msg', sa.String(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('theme',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    op.drop_table('logs')
    # ### end Alembic commands ###
